void setup() { 
  size(600, 800); //set size of canvas
  background(0); //sets background color to black
  strokeWeight(10); //stroke weight of the line will be thicker
}

void draw() {
  println(QFormula(2, 14, 3)); //initialize variables and display the number generated by the quadratic formula using the parameters inserted
  println(work(0.23, 4.5));  //initialize variables and display the work done by an object using the parameters inserted for mass and velocity
  spotlight(125, 45, 231, 20, 234); //initialize parameters for stroke, transparency, and origin of the light
}

float QFormula(float a, float b, float c) { //define function for quadratic formula and define parameters
  return (-b + sqrt( b*b - 4*a*c)) / (2*a); //return the results of the quadratic equation using the defined parameters
}
float work(float m, float v) { //define function for work and define paramters
  return 0.5*m*pow(v, 2); //return the results of the work formula using the defined parameters
}

void spotlight(float r, float g, float b, float t, float d) { //define function and define parameters
  stroke(r, g, b, t); //set stroke of lines
  line(d, 0, random(0, width), height); //create lines that start at d and branch out downward across the screen

  if (d < width) { //if the end of the line is less than the width, move over 1 pixel
    d++;
  } else { //if d is greater than the width return to 0
    d = 0;
  }
}